#!/bin/bash

task=$1

if [ "$task" = "createuser" ]
then
    username=$2
    userType=$3 #l - local / r - remote

    if [ "$userType" = "l" ]
    then
        mysql -u root -p -e "CREATE USER '${username}'@'localhost' IDENTIFIED BY '${username}123';"

    elif [ "$userType" = "r" ]
    then
        mysql -u root -p -e "CREATE USER '${username}'@'%' IDENTIFIED BY '${username}123';"
    else
        echo 'Bad parameters'
    fi

elif [ "$task" = "dropuser" ]
then
    username=$2
    userType=$3

    if [ "$userType" = "l" ]
    then
        mysql -u root -p -e "DROP USER '${username}'localhost'%';"

    elif [ "$userType" = "r" ]
    then
        mysql -u root -p -e "DROP USER '${username}'@'%';"
    else
        echo 'Bad parameters'
    fi

elif [ "$task" = "grantuser" ]
then
    username=$2;
    db=$3
    userType=$4

    if [ "$userType" = "l" ]
    then
        mysql -u root -p -e "GRANT ALL ON ${db}.* TO '${username}'@'localhost';"

    elif [ "$userType" = "r" ]
    then
        mysql -u root -p -e "GRANT ALL ON ${db}.* TO '${username}'@'%';"
    else
        echo 'Bad parameters'
    fi

elif [ "$task" = "revokeuser" ]
then
    username=$2;
    db=$3
    userType=$4

    if [ "$userType" = "l" ]
    then
        mysql -u root -p -e "REVOKE ALL PRIVILEGES ON ${db}.* FROM '${username}'@'localhost';"
    elif [ "$userType" = "r" ]
    then
        mysql -u root -p -e "REVOKE ALL PRIVILEGES ON ${db}.* FROM '${username}'@'%';"
    else
        echo 'Bad parameters'
    fi

elif [ "$task" = "createdb" ]
then
    dbname=$2
    mysql -u root -p -e "CREATE DATABASE ${dbname};"

elif [ "$task" = "dropdb" ]
then
    dbname=$2
    mysql -u root -p -e "DROP DATABASE ${dbname};"
else
	echo 'No option specyfied'
fi
