#!/bin/bash

task=$1

if [ "$task" = "createuser" ]
then
    username=$2
    userType=$3 #l - local / r - remote
    [ $userType = "r" ] && userType="%" || userType="localhost"

    mysql -u root -p -e "CREATE USER '${username}'@'${userType}' IDENTIFIED BY '${username}123';"

elif [ "$task" = "dropuser" ]
then
    username=$2
    userType=$3
    [ $userType = "r" ] && userType="%" || userType="localhost"

    mysql -u root -p -e "DROP USER '${username}'@'${userType}';"

elif [ "$task" = "grantuser" ]
then
    username=$2;
    db=$3
    userType=$4
    [ $userType = "r" ] && userType="%" || userType="localhost"

    mysql -u root -p -e "GRANT ALL ON ${db}.* TO '${username}'@'${userType}';"

elif [ "$task" = "revokeuser" ]
then
    username=$2;
    db=$3
    userType=$4
    [ $userType = "r" ] && userType="%" || userType="localhost"

    mysql -u root -p -e "REVOKE ALL PRIVILEGES ON ${db}.* FROM '${username}'@'{$userType}';"

elif [ "$task" = "createdb" ]
then
    dbname=$2
    mysql -u root -p -e "CREATE DATABASE ${dbname};"

elif [ "$task" = "dropdb" ]
then
    dbname=$2
    mysql -u root -p -e "DROP DATABASE ${dbname};"

elif [ "$task" = "exportdb" ]
then
    dbname=$2
    pathToFile=$3
    mysqldump -u root -p ${dbname} > ${pathToFile}

elif [ "$task" = "importdb" ]
then
    dbname=$2
    pathToFile=$3
    mysql -u root -p ${dbname} < ${pathToFile}
else
	echo 'No option specyfied'
fi
