#!/bin/dash
envName=${1:-dev} #enviroiment name: prod / dev / default dev

if [ -f "app/console" ]; then
    app/console cache:clear --env=$envName
    app/console assets:install --env=$envName
    app/console assetic:dump --env=$envName
else
	echo "--- You should be in project folder ---"
fi
