#!/bin/dash

#This scripts setup permissions for given directory or file (requires setacl)
#http://symfony.com/doc/current/book/installation.html

objects=${1:-"app/cache app/logs"} # objects to setup permissions
HTTPDUSER="www-data"

sudo setfacl -R -m u:"$HTTPDUSER":rwX -m u:`whoami`:rwX $dirsVar
sudo setfacl -dR -m u:"$HTTPDUSER":rwX -m u:`whoami`:rwX $dirsVar
sudo chown -R "$HTTPDUSER":"$HTTPDUSER" $dirsVar
